### ISSUE TITLE
Fragen zu Entwurf

### ISSUE THREAD

**Issue by bohgman** [npschipsch/DevilIn-Art#1]
Hallo. Uns sind heute erste Fragen aufgekommen.

1) Was soll in das Seitenmenü wenn es keine Untermenüs gibt wie bei Login oder Registrierung? Soll es dann leer bleiben?
2) Wie ist das mit dem Rating gemeint? Soll nur über Rating bewertet werden können (also hier alle Kategorien) oder auch in den einzelnen Kategorien (Pictures/Animations, Handcraftig)? Oder sind diese nur zum Ansehen?

**Comment by npschipsch** [comment]
1. It shall be empty when there are no sub menus.

2. Every upload, no matter to what section has to pass the Rating to go online. That means that every newly uploaded Content will be displayed and rated over two Buttons with either "Safe for Work" or "Not Safe for Work".
