### ISSUE TITLE
Offer&Search

### ISSUE THREAD

**Issue by kostoele** [npschipsch/DevilIn-Art#4]
Can you please give some examples or tips how should we exactly implement these web pages. @npschipsch  @DBuckenauer  :))

**Comment by DBuckenauer** [comment]
We'd like to have a short heading for each offer / search and a description afterwards.
e.g. One Piece kakao card [Anime][Copics]
by User123
Description of the characters and their poses, colors etc.

You can find all additional requirements for offer and search in our wiki.
